name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build HtmlToPDFCore/HtmlToPDFCore.csproj --configuration Release
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.0.0
      with:
        PROJECT_FILE_PATH: HtmlToPDFCore
        VERSION_FILE_PATH: HtmlToPDFCore
            
        
