name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build with dotnet
      run: dotnet build HtmlToPDFCore/HtmlToPDFCore.csproj --configuration Release
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Generate nuget package
      run: nuget pack --configuration Release HtmlToPDFCore.nuspec
      working-directory: ./HtmlToPDFCore
            
        
